version: '3'
services:
  keycloak:
    image: nafiislam964/oncampus:0.0.4.RELEASE
    container_name: keycloak
    restart: always
    ports:
      - 80:8080
      - 443:8443

    environment:
      - KEYCLOAK_ADMIN=oncampusbuet@gmail.com
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
